services:
  maf:
    container_name: maf
    user: admin
    image: maf:local
    build:
      # ../ here means relative to the docker-compose.yml file.
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    # You want the container to stay up forever while you're developing.
    command: sleep infinity
    volumes:
      - type: bind
        # ../ here means relative to the docker-compose.yml file.
        source: ../
        target: /opt/repo/
      # - type: volume
      #   source: example-renv-cache
      #   target: /opt/renv-cache
      # - type: bind
      #   source: /lustre/scratch124/<username>
      #   target: /lustre/scratch124/<username>
    networks:
      - local-default

networks:
  local-default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350
    ipam:
      config:
        - subnet: 192.168.4.0/24

